# Site settings
title: MIKE MEY's Git Site
header-img: "img/meditations_1.jpg"
tagline: "cn"  
description: "Mekong"  
baseurl: ""
url: "http://meikang168.github.io"  

# About/contact
owner: 
  name: "  Mekong"
  email: "meikang168@gmail.com"
  bio: "厦大生态学在学研究生，R语言初学者，数据分析。"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  
#twitter_username: 
github_username: meikang168
#facebook_username: Mike Smith
#weibo_username: 康梅奈尔
zhihu_username: 康梅奈尔

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Beijing

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Mekong"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : cnfeat
  disqus :
      short_name : cnfeat

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
